name: Update maps
on:
  schedule:
    - cron: 0/10 * * * *

jobs:
  update_charts:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          conda install geopandas

      - name: Update BC flood warning chart
        env: 
            DW_AUTH_TOKEN: ${{ secrets.DW_AUTH_TOKEN }}
        run: python3 script-bcfloods.py
